version: "3"

services:
    nginx:
        image: nginx
        ports:
            - 8765:80
        volumes:
            - ./public/:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    npm:
        image: node
        user: node
        entrypoint: npm
        working_dir: /home/node
        volumes:
            - .:/home/node

    node:
        image: node
        user: node
        entrypoint: node
        working_dir: /home/node
        volumes:
            - .:/home/node

    shell:
        image: node
        user: node
        working_dir: /home/node
        volumes:
            - .:/home/node
